---
AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS API GW creation with Usage Plans"

Parameters:
    ApiKeySourceType:
        Type: String
    RestApiRandomGetIntegrationUri:
        Type: String

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: !Sub '${AWS::StackName}-apigw'
      Name: !Sub '${AWS::StackName}-apigw'
      ApiKeySourceType: !Ref ApiKeySourceType
      EndpointConfiguration:
        Types:
        - REGIONAL


  RestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RestApi
    Properties:
      RestApiId: !Ref RestApi
      Description: Automatically created by the RestApi construct
    DependsOn:
      - RestApiRandomGet


  RestApiDeploymentStageDev:
    Type: AWS::ApiGateway::Stage
    DependsOn:
      - RestApi
    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref RestApiDeployment
      StageName: dev

  RestApiRandom:
    Type: AWS::ApiGateway::Resource
    DependsOn:
      - RestApi
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: "random"
      RestApiId: !Ref RestApi

  RestApiRandomGet:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - RestApi
    Properties:
      HttpMethod: GET
      ResourceId: !Ref RestApiRandom
      RestApiId: !Ref RestApi
      ApiKeyRequired: true
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: GET
        Type: HTTP
        Uri: !Ref RestApiRandomGetIntegrationUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "application/json": "Empty" }

  ApiKeyGoldenUser01:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      Name: ApiKeyGoldenUser01
      Description: CloudFormation API Key for GoldenUser01
      Enabled: true
      StageKeys:
        - RestApiId: !Ref RestApi
          StageName: dev


  UsagePlanKeyGoldenUser01:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      KeyId: !Ref ApiKeyGoldenUser01
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlanGolden

  ApiKeyGoldenUser02:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      Name: ApiKeyGoldenUser02
      Description: CloudFormation API Key for GoldenUser02
      Enabled: true
      StageKeys:
        - RestApiId: !Ref RestApi
          StageName: dev


  UsagePlanKeyGoldenUser02:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      KeyId: !Ref ApiKeyGoldenUser02
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlanGolden

  ApiKeySilverUser01:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      Name: ApiKeySilverUser01
      Description: CloudFormation API Key for SilverUser01
      Enabled: true
      StageKeys:
        - RestApiId: !Ref RestApi
          StageName: dev


  UsagePlanKeySilverUser01:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      KeyId: !Ref ApiKeySilverUser01
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlanSilver


  ApiKeySilverUser02:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      Name: ApiKeySilverUser02
      Description: CloudFormation API Key for SilverUser02
      Enabled: true
      StageKeys:
        - RestApiId: !Ref RestApi
          StageName: dev


  UsagePlanKeySilverUser02:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      KeyId: !Ref ApiKeySilverUser02
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlanSilver

  ApiKeyBronzeUser01:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      Name: ApiKeyBronzeUser01
      Description: CloudFormation API Key for BronzeUser01
      Enabled: true
      StageKeys:
        - RestApiId: !Ref RestApi
          StageName: dev


  UsagePlanKeyBronzeUser01:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      KeyId: !Ref ApiKeyBronzeUser01
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlanBronze



  ApiKeyBronzeUser02:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      Name: ApiKeyBronzeUser02
      Description: CloudFormation API Key for BronzeUser02
      Enabled: true
      StageKeys:
        - RestApiId: !Ref RestApi
          StageName: dev


  UsagePlanKeyBronzeUser02:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      KeyId: !Ref ApiKeyBronzeUser02
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlanBronze

  UsagePlanGolden:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: dev
      Description: Golden Class Customers
      Quota:
        Limit: 15
        Period: MONTH
      Throttle:
        BurstLimit: 12
        RateLimit: 10
      UsagePlanName: GoldenClass

  UsagePlanSilver:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: dev
      Description: Silver Class Customers
      Quota:
        Limit: 10
        Period: MONTH
      Throttle:
        BurstLimit: 8
        RateLimit: 6
      UsagePlanName: SilverClass

  UsagePlanBronze:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - RestApi
      - RestApiDeploymentStageDev
    Properties:
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: dev
      Description: Bronze Class Customers
      Quota:
        Limit: 5
        Period: MONTH
      Throttle:
        BurstLimit: 4
        RateLimit: 13
      UsagePlanName: BronzeClass


Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref RestApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/'
